name: deployment
on: push
jobs:
    deps:
      runs-on: ubuntu-latest
      steps:
        - name: Get Code
          uses: actions/checkout@v3
        - name: install dependencies
          run: npm ci
    lint:
      needs: deps
      runs-on: ubuntu-latest
      steps:   
        - name: Get Code
          uses: actions/checkout@v3
        - name: install dependencies
          run: npm ci
        - name: build
          run: npm run build
        - name: lint
          run: npm run lint
    deploy:
       needs: deps
       runs-on: ubuntu-latest
       steps:
         - name: Deploy
           run: echo "deploying ..."

    